module.exports = {
  content: ["./pages/**/*.{html,js}", "./components/**/*.{html,js}"],
  darkMode: "media",
  theme: {
    borderWidth: {
      DEFAULT: "1px",
      0: "0",
      1: "1px",
      2: "2px",
      3: "3px",
      4: "4px",
      6: "6px",
      8: "8px",
    },
    fontSize: {
      tiny: ".55rem",
      xs: ".75rem",
      sm: ".875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
      "6xl": "4rem",
      "7xl": "5rem",
    },
    extend: {
      colors: {
        white: "#FFFFFF",
        black: "#000000",
        BLUE: "#187498",
        BLUE50: "#4f46e5",
        BLUE100: "#17B9B4",
        BLUEDARK: "#45378B",
        Purp: "#581c87",
        Purp100: "#45378B",
        Purp200: "#695CAD",
        Purp300: "#453783",
        Purp400: "#382F68",
        Purp500: "#322A8A",
        GREEN: "#36AE7C",
        GREEN100: "#17C1BC",
        YELLOW: "#E0A719",
        SKY: "#17C1BC",
        "red-600": "#991b1b",
        "red-800": "#991b1b",
        GRAY: "#CCCCCC",
        basicGray: "#D9D9D9",
        GRAYLIGHT: "#EAE9E9",
        GRAY50: "#B0B0B0",
        GRAY100: "#F5F5F5",
        GRAY200: "#DDDDDD",
        GRAY300: "#7F7F7F",
        GRAY400: "#686767",
        palette: {
          gray: {
            basicGray: "#B0B0B0",
            lighterGray: "#6F6C90",
            lightGray: "#BEBEBE",
            medGray: "#DDDDDD",
            semiGray: "#7F7F7F",
            darkGray: "#686767",
          },
          purple: {
            basicPurple: "#581c87",
            lightPurple: "#695CAD",
            medPurple: "#45378B",
            darkPurple: "#3E3175",
            darkerPurple: "#170F49",
          },
          cyan: {
            lightCyan: "#17C1BC",
            medCyan: "#17B9B4",
          },
          red: {
            lightRed: "#EB5353",
            darkRed: "#980000",
          },
          blue: {
            lightBlue: "#187498",
            darkBlue: "#156382",
          },
          green: {
            lightGreen: "#36AE7C",
            darkGreen: "#309c6f",
          },
          yellow: {
            lightYellow: "#E0A719",
            darkYellow: "#c99616",
          },
        },
      },
      backgroundImage: {
        jordan: "url('/assest/images/jordan.jpg')",
        kuwait: "url('/assest/images/kuwait.jpg')",
        saudi: "url('/assest/images/saudi.jpg')",
        egypt: "url('/assest/images/egypt.jpg')",
        mobileJordan: "url('/assest/images/mobileJordan.jpg')",
        mobileKuwait: "url('/assest/images/mobileKuwait.jpg')",
        mobileSaudi: "url('/assest/images/mobileSaudi.jpg')",
        mobileEgypt: "url('/assest/images/mobileEgypt.jpg')",
        "fifth-bg": "url('/assest/images/images/Fifth-bg.png')",
        "branding-outlines":
          "url('/assest/images/images/branding-outlines.png')",
        "circle-center": "url('/assest/images/images/circle-center.png')",
        // mobile: "url('./assets/images/mobile.png')",
      },
      fontFamily: {
        TSExtra: ["TsExtrabold"],
        TSSemi: ["TsSemibold"],
        TSbold: ["Tsbold"],
        TSmedium: ["TsMed"],
        TSregular: ["TsReg"],
      },
    },
    gradientColorStops: (theme) => ({
      primary: "#45378B",
      secondary: "#1D1C90",
    }),
  },
  variants: {
    extend: {},
  },
  plugins: [require("tailwindcss-rtl")],
};
// colors: {
//   white: '#FFFFFF',
//   black: '#000000',
//   BLUE: '#187498',
//   BLUE50: '#4f46e5',
//   BLUE100: '#17B9B4',
//   BLUEDARK: '#45378B',
//   Purp: '#581c87',
//   Purp100: '#45378B',
//   Purp200: '#695CAD',
//   Purp300: '#453783',
//   Purp400: '#382F68',
//   Purp500: '#322A8A',
//   GREEN: '#36AE7C',
//   GREEN100: '#17C1BC',
//   YELLOW: '#E0A719',
//   SKY: '#17C1BC',
//   RED: '#EB5353',
//   'red-600': '#991b1b',
//   'red-800': '#991b1b',
//   GRAY: '#CCCCCC',
//   GRAYLIGHT: '#EAE9E9',
//   GRAY50: '#B0B0B0',
//   GRAY100: '#F5F5F5',
//   GRAY200: '#DDDDDD',
//   GRAY300: '#7F7F7F',
//   GRAY400: '#686767',
// },
// backgroundImage: (theme) => ({
//   'fifth-bg': "url('/assest/images/images/Fifth-bg.png')",
//   'branding-outlines': "url('/assest/images/images/branding-outlines.png')",
//   'circle-center': "url('/assest/images/images/circle-center.png')",
//   // mobile: "url('./assets/images/mobile.png')",
// }),
